<div class="Größe_ption">
  <label for="Größe">Größe:</label>
  <select id="product_Größe">
    <option value="Größe">Wähle deine Größe</option>
    <option value="Größe">Wähle deine Größe</option>
    <option value="Größe">Größe</option>
  </select>
</div>

<div class="Größe_ption">
  <label for="Größe">Größentabelle:</label>
  <select id="product_Größe">
    <option value="Größe">Wähle deine Größe</option>
    <option value="Größe">Wähle deine Größe</option>
    <option value="Größe">Größe</option>
  </select>
</div>
