<div class="footer_section">
	<div class="footer_container">
		<div class="footer_details">
			<div class="footer_item company_info">
				<div class="footer_title">COMPANY INFORMATION</div>
				<div class="footer_company_details">
					<div class="company_item">
						<p><a href="#">Blog</a></p>
						<p><a href="#">Store location</a></p>
						<p><a href="#">Privacy policy</a></p>
						<p><a href="#">Terms of Use</a></p>
						<p><a href="#">About Us</a></p>
					</div>
					<div class="company_item">
						<p><a href="#">Order Status</a></p>
						<p><a href="#">Wishlist</a></p>
						<p><a href="#">My Account</a></p>
						<p><a href="#">Returns and Exchanges</a></p>
						<p><a href="#">Carriers</a></p>
						<p><a href="#">Shipping</a></p>
					</div>
				</div>
			</div>
			<div class="footer_item det_social">
				<div class="det_social_details">
					<div class="footer_title">GET SOCIAL</div>
					<p>Join our on Facebook and get recent news about our new products and offers.</p>
					<div class="social_icon">
						<div class="twitter_icon"></div>
						<div class="facebook_icon"></div>
						<div class="youtube_icon"></div>
						<div class="wifi_icon"></div>
					</div>
				</div>
				<div class="newsletter">
					<div class="footer_title">NEWSLETTER</div>
					<div class="footer_subscriber">
						<?php echo $this->getLayout()->createBlock("Magento\Newsletter\Block\Subscribe")->setTemplate("Magento_Newsletter::subscribe.phtml")->toHtml() ?> 
					</div>
				</div>
			</div>
			<div class="footer_item about_us">
				<div class="footer_title">ABOUT US</div>
				<div class="address_footer">
					<p>221B Baker Street</p>
					<p>West Windsor, NJ 08550</p>
					<p>1.800.555.1903</p>
				</div>
				<p>Natural Herbs is truly professional company on vitamine and sport nutrition supplements' marketplace. We sell only the highest-grade substances needed for health and bodily growth. Our web-store offers a huge choice of products for better physical wellbeing. Let's engage people to be healthy!</p>
				<img width="302" height="33" style="margin: 5px 0 7px;" src="https://argento-m2.swissupdemo.com/static/frontend/Swissup/argento-flat/en_US/images/payments.png" alt="Credit cards, we accept" loading="lazy">
			</div>
		</div>
	</div>
</div>