<!-- $this->helper('Dolphin\SocialShare\Helper\Data')->isEnabledfb();  -->
<?php
$_product = $block->getProduct(); // GET THE PRODUCT
?>

<div class="shareicon">
    <p class="share">share</p>

    <?php $helper= $this->helper('Dolphin\SocialShare\Helper\Data'); ?> 
    <div class="social_main">
        <div class="social_icon">     
            <?php if($helper->isEnabled() == 1): ?>
                <a href="https://instagram.com/send?text=<?php echo urlencode($_product->getProductUrl());?>&t=<?php echo urlencode($_product->getName())?>" class="custom-icon-instaa">
            <?php endif; ?>

            <?php if($helper->isEnabledfb() == 1): ?>
                <a class="custom-icon-fb" target="_blank" rel="noopener" href="//www.facebook.com/sharer.php?u=<?php echo $_product->getProductUrl();?>">
              </a>
            <?php endif; ?>

            <?php if($helper->isEnabledtwitter() == 1): ?>
                <a href="https://twitter.com/intent/tweet?text=<?php echo urlencode($_product->getProductUrl());?>&t=<?php echo urlencode($_product->getName())?>" class="custom-icon-twitter">
                </a>
            <?php endif; ?>

            <?php if($helper->isEnabledwhatsapp() == 1): ?>
                <a href="https://web.whatsapp.com/send?text=<?php echo urlencode($_product->getProductUrl());?>&t=<?php echo urlencode($_product->getName())?>" class="custom-icon-whatsapp">
                </a>
            <?php endif; ?>

            <?php if($helper->isEnabledpinterest() == 1): ?>
                <a href="https://in.pinterest.com/send?text=<?php echo urlencode($_product->getProductUrl());?>&t=<?php echo urlencode($_product->getName())?>" class="custom-icon-pinterest">
                </a>
            <?php endif; ?>

            <a href="https://twitter.com/intent/tweet?text=<?php echo urlencode($_product->getProductUrl());?>&t=<?php echo urlencode($_product->getName())?>" class="custom-icon-image">
                <img class="getimage" src="<?= $helper->getMediaUrl() . '/' . $helper->issEnabledshare() ?>">
            </a>

        </div>
    </div>
</div>
