<h1>hello world</h1>
<!-- $this->helper('Dolphin\SocialShare\Helper\Data')->isEnabledfb();  -->
?= $this->helper('Dolphin\SocialShare\Helper\Data')->getProductUrl(); ?>

<?php
$_product = $block->getProduct(); // GET THE PRODUCT

?>

<?php $helper= $this->helper('Dolphin\SocialShare\Helper\Data'); ?> 
<div class="social_icon">     
    <?php if($helper->isEnabled() == 1): ?>
          <a class="custom-icon-insta" href="https://www.instagram.com">
          </a>
    <?php endif; ?>

    <?php if($helper->isEnabledfb() == 1): ?>
         <a href="https://www.facebook.com/sharer/sharer.php" class="custom-icon-fb"></a>
    <?php endif; ?>

    <?php if($helper->isEnabledtwitter() == 1): ?>
         <a href=" http://twitter.com/home" class="custom-icon-twitter"></a>
    <? else: ?>
        <a href="website_name.com">elase</a>
    <?php endif; ?>
</div>

