<div class="footer_main">
	<div class="footer_container">
		<div class="footer_section">
			<div class="footer_items">
				<h2 class="footer_contact_heading">CONTACT INFO</h2>
				<div class="footer_contact_items">
					<div class="porto_info">
						<div class="porto-u-main-heading"><div>ADDRESS:</div></div>
						<div class="porto-u-sub-heading">123 Street Name, City, England</div>
					</div>
					<div class="porto_info">
						<div class="porto-u-main-heading"><div>PHONE:</div></div>
						<div class="porto-u-sub-heading">(123) 456-7890</div>
					</div>
					<div class="porto_info">
						<div class="porto-u-main-heading"><div>EMAIL:</div></div>
						<div class="porto-u-sub-heading">mail@example.com</div>
					</div>
					<div class="porto_info">
						<div class="porto-u-main-heading"><div>WORKING DAYS/HOURS:</div></div>
						<div class="porto-u-sub-heading">Mon - Sun / 9:00 AM - 8:00 PM</div>
					</div>
					<div class="social_icon">
						<a href="#" class="share-facebook">
							
						</a>
						<a href="#" class="share-twitter">
							
						</a>
						<a href="#" class="share-instagram">
							
						</a>
					</div>
				</div>
			</div>
			<div class="footer_items">
				<h2 class="footer_contact_heading">CONTACT INFO</h2>
				<div class="footer_contact_items">
					<div class="footer_link">
						<a href="#">Help & FAQs</a>
						<a href="#">Order Tracking</a>
						<a href="#">Shipping & Delivery</a>
						<a href="#">Orders History</a>
						<a href="#">Advanced Search</a>
						<a href="#">My Account</a>
						<a href="#">Careers</a>
						<a href="#">About Us</a>
						<a href="#">Corporate Sales</a>
						<a href="#">Privacy</a>
					</div>
				</div>
			</div>
			<div class="footer_items">
				<h2 class="footer_contact_heading">POPULAR TAGS</h2>
				<div class="footer_contact_items">
					<div class="tagcloud">
						<a href="#" class="tag-cloud-link">Bag</a>
						<a href="#" class="tag-cloud-link">black</a>
						<a href="#" class="tag-cloud-link">blue</a>
						<a href="#" class="tag-cloud-link">Clothes</a>
						<a href="#" class="tag-cloud-link">Fashion</a>
						<a href="#" class="tag-cloud-link">Hub</a>
						<a href="#" class="tag-cloud-link">Shirt</a>
						<a href="#" class="tag-cloud-link">shoes</a>
						<a href="#" class="tag-cloud-link">Skirt</a>
						<a href="#" class="tag-cloud-link">Sports</a>
						<a href="#" class="tag-cloud-link">Sweater</a>
					</div>
				</div>
			</div>
			<div class="footer_items">
				<h2 class="footer_contact_heading">SUBSCRIBE NEWSLETTER</h2>
				<div class="footer_contact_items">
					<div class="porto-u-sub-heading">Get all the latest information on events, sales and offers. Sign up for newsletter:</div>
					<div class="custom_form">
						<!-- <div class="input_email">
					        <span class="form_control_wrap">
					        	<input type="email" name="your-email" value="" size="40" class="wpcf7_email" aria-required="true" aria-invalid="false" placeholder="Email address">
					        </span>
					    </div>
						<div class="submit_btn">
					        <input type="submit" value="SUBSCRIBE" class="form_control_btn"><span class="wpcf7-spinner"></span>
					    </div> -->
					    <?php echo $this->getLayout()->createBlock("Magento\Newsletter\Block\Subscribe")->setTemplate("Magento_Newsletter::subscribe.phtml")->toHtml() ?> 
					</div>
				</div>
			</div>
		</div>
	</div>
</div>