<div class="porto_contact_icon">
	<div class="contact_icon"></div>
	<div class="porto-sicon-header">
		<a href="tel:1235678890">
			<h3 class="porto-sicon-title">Call Us Now</h3>
			<p>+123 5678 890</p>
		</a>
	</div>
</div>

<a href="<?php echo $this->getUrl('customer/account/login') ?>" title="My Account" class="porto_link_login">
	<i class="porto-icon-user"></i>
</a>

<a href="<?php echo $this->getUrl('wishlist') ?>" title="Wishlist" class="porto_link_Wishlist">
	<i class="porto-icon-Wishlist"></i>
</a>
