<div id="top" class="nav_section">
  <ul class="item_link">
    <li class="nav-item active"><a class="nav-link" href="javascript:void(0)" data-id="#section-1">Section 1</a></li>
    <li class="nav-item"><a class="nav-link" href="javascript:void(0)" data-id="#section-2">Section 2</a></li>
    <li class="nav-item"><a class="nav-link" href="javascript:void(0)" data-id="#section-3">Section 3</a></li>
    <li class="nav-item"><a class="nav-link" href="javascript:void(0)" data-id="#section-4">Section 4</a></li>
    <li class="nav-item"><a class="nav-link" href="javascript:void(0)" data-id="#section-5">Section 5</a></li>
    <li class="nav-item"><a class="nav-link" href="javascript:void(0)" data-id="#section-6">Section 6</a></li>
  </ul> 
</div>
