<div class="testing" id="section-5">
	<div class="adventures-inner" >
	<h1 class="section_title">
		section-5
	</h1>
		<div class="family-adventures">
			<div class="travel">
				<div class="travel-contain">
					<h1>Best <span style="color:var(--orange);"> family adventures</span> for 2022</h1>
					<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book</p>
					<button>Learn more</button>
				</div>
			</div>
		</div>

		<div class="Chicago-City">
			<div class="travels">
				<div class="travel-contain">
					<h1>Adventures of <span style="color:var(--orange);">Chicago City </span> </h1>
					<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book</p>
					<button>Learn more</button>
				</div>
					
			</div>
		</div>
	</div>
</div>

<div class="testing" id="section-6">
	<h1 class="section_title">section-6</h1>
	<div class="adventures-inner-two">
		<div class="family-adventures">
			<div class="travel">
				<div class="travel-contain">
					<h1>Best <span style="color:var(--orange);"> section-6 adventures</span> for 2022</h1>
					<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book</p>
					<button>Learn more</button>
				</div>
			</div>
		</div>

		<div class="Chicago-City">
			<div class="travels">
				<div class="travel-contain">
					<h1>Adventures of <span style="color:var(--orange);">Chicago City </span> </h1>
					<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book</p>
					<button>Learn more</button>
				</div>
					
			</div>
		</div>
	</div>
</div>